onerror {resume}
quietly virtual function -install /TestReadMem/the_dut/m_axis_em_to_fil1 -env /TestReadMem { &{/TestReadMem/the_dut/m_axis_em_to_fil1/tdata[31], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[30], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[29], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[28], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[27], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[26], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[25], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[24], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[23], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[22], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[21], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[20], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[19], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[18], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[17], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[16], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[15], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[14], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[13], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[12], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[11], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[10], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[9], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[8], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[7], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[6], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[5], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[4], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[3], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[2], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[1], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[0] }} bem_k
quietly virtual function -install /TestReadMem/the_dut/m_axis_em_to_fil1 -env /TestReadMem { &{/TestReadMem/the_dut/m_axis_em_to_fil1/tdata[63], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[62], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[61], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[60], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[59], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[58], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[57], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[56], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[55], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[54], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[53], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[52], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[51], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[50], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[49], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[48], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[47], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[46], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[45], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[44], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[43], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[42], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[41], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[40], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[39], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[38], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[37], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[36], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[35], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[34], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[33], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[32] }} bem_l
quietly virtual function -install /TestReadMem/the_dut/m_axis_em_to_fil1 -env /TestReadMem { &{/TestReadMem/the_dut/m_axis_em_to_fil1/tdata[95], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[94], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[93], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[92], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[91], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[90], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[89], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[88], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[87], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[86], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[85], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[84], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[83], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[82], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[81], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[80], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[79], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[78], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[77], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[76], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[75], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[74], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[73], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[72], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[71], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[70], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[69], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[68], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[67], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[66], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[65], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[64] }} bem_s
quietly virtual function -install /TestReadMem/the_dut/m_axis_em_to_fil1 -env /TestReadMem { &{/TestReadMem/the_dut/m_axis_em_to_fil1/tdata[107], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[106], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[105], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[104], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[103], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[102], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[101], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[100], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[99], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[98], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[97], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[96] }} bem_i
quietly virtual function -install /TestReadMem/the_dut/m_axis_em_to_fil1 -env /TestReadMem { &{/TestReadMem/the_dut/m_axis_em_to_fil1/tdata[119], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[118], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[117], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[116], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[115], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[114], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[113], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[112], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[111], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[110], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[109], /TestReadMem/the_dut/m_axis_em_to_fil1/tdata[108] }} bem_j
quietly virtual function -install /TestReadMem/m_axis_emout -env /TestReadMem { &{/TestReadMem/m_axis_emout/tdata[31], /TestReadMem/m_axis_emout/tdata[30], /TestReadMem/m_axis_emout/tdata[29], /TestReadMem/m_axis_emout/tdata[28], /TestReadMem/m_axis_emout/tdata[27], /TestReadMem/m_axis_emout/tdata[26], /TestReadMem/m_axis_emout/tdata[25], /TestReadMem/m_axis_emout/tdata[24], /TestReadMem/m_axis_emout/tdata[23], /TestReadMem/m_axis_emout/tdata[22], /TestReadMem/m_axis_emout/tdata[21], /TestReadMem/m_axis_emout/tdata[20], /TestReadMem/m_axis_emout/tdata[19], /TestReadMem/m_axis_emout/tdata[18], /TestReadMem/m_axis_emout/tdata[17], /TestReadMem/m_axis_emout/tdata[16], /TestReadMem/m_axis_emout/tdata[15], /TestReadMem/m_axis_emout/tdata[14], /TestReadMem/m_axis_emout/tdata[13], /TestReadMem/m_axis_emout/tdata[12], /TestReadMem/m_axis_emout/tdata[11], /TestReadMem/m_axis_emout/tdata[10], /TestReadMem/m_axis_emout/tdata[9], /TestReadMem/m_axis_emout/tdata[8], /TestReadMem/m_axis_emout/tdata[7], /TestReadMem/m_axis_emout/tdata[6], /TestReadMem/m_axis_emout/tdata[5], /TestReadMem/m_axis_emout/tdata[4], /TestReadMem/m_axis_emout/tdata[3], /TestReadMem/m_axis_emout/tdata[2], /TestReadMem/m_axis_emout/tdata[1], /TestReadMem/m_axis_emout/tdata[0] }} k
quietly virtual function -install /TestReadMem/m_axis_emout -env /TestReadMem { &{/TestReadMem/m_axis_emout/tdata[63], /TestReadMem/m_axis_emout/tdata[62], /TestReadMem/m_axis_emout/tdata[61], /TestReadMem/m_axis_emout/tdata[60], /TestReadMem/m_axis_emout/tdata[59], /TestReadMem/m_axis_emout/tdata[58], /TestReadMem/m_axis_emout/tdata[57], /TestReadMem/m_axis_emout/tdata[56], /TestReadMem/m_axis_emout/tdata[55], /TestReadMem/m_axis_emout/tdata[54], /TestReadMem/m_axis_emout/tdata[53], /TestReadMem/m_axis_emout/tdata[52], /TestReadMem/m_axis_emout/tdata[51], /TestReadMem/m_axis_emout/tdata[50], /TestReadMem/m_axis_emout/tdata[49], /TestReadMem/m_axis_emout/tdata[48], /TestReadMem/m_axis_emout/tdata[47], /TestReadMem/m_axis_emout/tdata[46], /TestReadMem/m_axis_emout/tdata[45], /TestReadMem/m_axis_emout/tdata[44], /TestReadMem/m_axis_emout/tdata[43], /TestReadMem/m_axis_emout/tdata[42], /TestReadMem/m_axis_emout/tdata[41], /TestReadMem/m_axis_emout/tdata[40], /TestReadMem/m_axis_emout/tdata[39], /TestReadMem/m_axis_emout/tdata[38], /TestReadMem/m_axis_emout/tdata[37], /TestReadMem/m_axis_emout/tdata[36], /TestReadMem/m_axis_emout/tdata[35], /TestReadMem/m_axis_emout/tdata[34], /TestReadMem/m_axis_emout/tdata[33], /TestReadMem/m_axis_emout/tdata[32] }} l
quietly virtual function -install /TestReadMem/m_axis_emout -env /TestReadMem { &{/TestReadMem/m_axis_emout/tdata[95], /TestReadMem/m_axis_emout/tdata[94], /TestReadMem/m_axis_emout/tdata[93], /TestReadMem/m_axis_emout/tdata[92], /TestReadMem/m_axis_emout/tdata[91], /TestReadMem/m_axis_emout/tdata[90], /TestReadMem/m_axis_emout/tdata[89], /TestReadMem/m_axis_emout/tdata[88], /TestReadMem/m_axis_emout/tdata[87], /TestReadMem/m_axis_emout/tdata[86], /TestReadMem/m_axis_emout/tdata[85], /TestReadMem/m_axis_emout/tdata[84], /TestReadMem/m_axis_emout/tdata[83], /TestReadMem/m_axis_emout/tdata[82], /TestReadMem/m_axis_emout/tdata[81], /TestReadMem/m_axis_emout/tdata[80], /TestReadMem/m_axis_emout/tdata[79], /TestReadMem/m_axis_emout/tdata[78], /TestReadMem/m_axis_emout/tdata[77], /TestReadMem/m_axis_emout/tdata[76], /TestReadMem/m_axis_emout/tdata[75], /TestReadMem/m_axis_emout/tdata[74], /TestReadMem/m_axis_emout/tdata[73], /TestReadMem/m_axis_emout/tdata[72], /TestReadMem/m_axis_emout/tdata[71], /TestReadMem/m_axis_emout/tdata[70], /TestReadMem/m_axis_emout/tdata[69], /TestReadMem/m_axis_emout/tdata[68], /TestReadMem/m_axis_emout/tdata[67], /TestReadMem/m_axis_emout/tdata[66], /TestReadMem/m_axis_emout/tdata[65], /TestReadMem/m_axis_emout/tdata[64] }} s
quietly virtual function -install /TestReadMem/m_axis_emout -env /TestReadMem { &{/TestReadMem/m_axis_emout/tdata[107], /TestReadMem/m_axis_emout/tdata[106], /TestReadMem/m_axis_emout/tdata[105], /TestReadMem/m_axis_emout/tdata[104], /TestReadMem/m_axis_emout/tdata[103], /TestReadMem/m_axis_emout/tdata[102], /TestReadMem/m_axis_emout/tdata[101], /TestReadMem/m_axis_emout/tdata[100], /TestReadMem/m_axis_emout/tdata[99], /TestReadMem/m_axis_emout/tdata[98], /TestReadMem/m_axis_emout/tdata[97], /TestReadMem/m_axis_emout/tdata[96] }} i
quietly virtual function -install /TestReadMem/m_axis_emout -env /TestReadMem { &{/TestReadMem/m_axis_emout/tdata[119], /TestReadMem/m_axis_emout/tdata[118], /TestReadMem/m_axis_emout/tdata[117], /TestReadMem/m_axis_emout/tdata[116], /TestReadMem/m_axis_emout/tdata[115], /TestReadMem/m_axis_emout/tdata[114], /TestReadMem/m_axis_emout/tdata[113], /TestReadMem/m_axis_emout/tdata[112], /TestReadMem/m_axis_emout/tdata[111], /TestReadMem/m_axis_emout/tdata[110], /TestReadMem/m_axis_emout/tdata[109], /TestReadMem/m_axis_emout/tdata[108] }} j
quietly WaveActivateNextPane {} 0
add wave -noupdate /TestReadMem/clk
add wave -noupdate /TestReadMem/rst
add wave -noupdate /TestReadMem/read
add wave -noupdate /TestReadMem/start
add wave -noupdate /TestReadMem/finish
add wave -noupdate /TestReadMem/busy
add wave -noupdate /TestReadMem/emout_handsk
add wave -noupdate /TestReadMem/m_axis_emout/tvalid
add wave -noupdate /TestReadMem/m_axis_emout/tready
add wave -noupdate -radix unsigned /TestReadMem/m_axis_emout/k
add wave -noupdate -radix unsigned /TestReadMem/m_axis_emout/l
add wave -noupdate -radix unsigned /TestReadMem/m_axis_emout/s
add wave -noupdate -radix unsigned /TestReadMem/m_axis_emout/i
add wave -noupdate -radix unsigned /TestReadMem/m_axis_emout/j
add wave -noupdate /TestReadMem/m_axis_emout/tdata
add wave -noupdate -divider DUT
add wave -noupdate /TestReadMem/the_dut/gd_read
add wave -noupdate -radix unsigned /TestReadMem/the_dut/pos
add wave -noupdate /TestReadMem/the_dut/bem_start
add wave -noupdate /TestReadMem/the_dut/bem_finish
add wave -noupdate /TestReadMem/the_dut/bem_busy
add wave -noupdate -radix unsigned /TestReadMem/the_dut/m_axis_em_to_fil1/bem_k
add wave -noupdate -radix unsigned /TestReadMem/the_dut/m_axis_em_to_fil1/bem_l
add wave -noupdate -radix unsigned /TestReadMem/the_dut/m_axis_em_to_fil1/bem_s
add wave -noupdate -radix unsigned /TestReadMem/the_dut/m_axis_em_to_fil1/bem_i
add wave -noupdate -radix unsigned /TestReadMem/the_dut/m_axis_em_to_fil1/bem_j
add wave -noupdate /TestReadMem/the_dut/m_axis_em_to_fil1/tvalid
add wave -noupdate /TestReadMem/the_dut/m_axis_em_to_fil1/tready
add wave -noupdate -divider Fil1
add wave -noupdate /TestReadMem/the_dut/the_fil1/start
add wave -noupdate /TestReadMem/the_dut/the_fil1/stop
add wave -noupdate /TestReadMem/the_dut/the_fil1/finish
add wave -noupdate /TestReadMem/the_dut/the_fil1/busy
add wave -noupdate -radix unsigned /TestReadMem/the_dut/the_fil1/state
add wave -noupdate -radix unsigned /TestReadMem/the_dut/the_fil1/nxt_state
add wave -noupdate -radix unsigned /TestReadMem/the_dut/the_fil1/cnt
add wave -noupdate -childformat {{{/TestReadMem/the_dut/the_fil1/m[0]} -radix unsigned -childformat {{{/TestReadMem/the_dut/the_fil1/m[0].j} -radix unsigned} {{/TestReadMem/the_dut/the_fil1/m[0].i} -radix unsigned} {{/TestReadMem/the_dut/the_fil1/m[0].s} -radix unsigned} {{/TestReadMem/the_dut/the_fil1/m[0].l} -radix unsigned} {{/TestReadMem/the_dut/the_fil1/m[0].k} -radix unsigned}}} {{/TestReadMem/the_dut/the_fil1/m[1]} -radix unsigned -childformat {{{/TestReadMem/the_dut/the_fil1/m[1].j} -radix unsigned} {{/TestReadMem/the_dut/the_fil1/m[1].i} -radix unsigned} {{/TestReadMem/the_dut/the_fil1/m[1].s} -radix unsigned} {{/TestReadMem/the_dut/the_fil1/m[1].l} -radix unsigned} {{/TestReadMem/the_dut/the_fil1/m[1].k} -radix unsigned}}} {{/TestReadMem/the_dut/the_fil1/m[2]} -radix unsigned} {{/TestReadMem/the_dut/the_fil1/m[3]} -radix unsigned}} -subitemconfig {{/TestReadMem/the_dut/the_fil1/m[0]} {-height 27 -radix unsigned -childformat {{{/TestReadMem/the_dut/the_fil1/m[0].j} -radix unsigned} {{/TestReadMem/the_dut/the_fil1/m[0].i} -radix unsigned} {{/TestReadMem/the_dut/the_fil1/m[0].s} -radix unsigned} {{/TestReadMem/the_dut/the_fil1/m[0].l} -radix unsigned} {{/TestReadMem/the_dut/the_fil1/m[0].k} -radix unsigned}}} {/TestReadMem/the_dut/the_fil1/m[0].j} {-height 27 -radix unsigned} {/TestReadMem/the_dut/the_fil1/m[0].i} {-height 27 -radix unsigned} {/TestReadMem/the_dut/the_fil1/m[0].s} {-height 27 -radix unsigned} {/TestReadMem/the_dut/the_fil1/m[0].l} {-height 27 -radix unsigned} {/TestReadMem/the_dut/the_fil1/m[0].k} {-height 27 -radix unsigned} {/TestReadMem/the_dut/the_fil1/m[1]} {-height 27 -radix unsigned -childformat {{{/TestReadMem/the_dut/the_fil1/m[1].j} -radix unsigned} {{/TestReadMem/the_dut/the_fil1/m[1].i} -radix unsigned} {{/TestReadMem/the_dut/the_fil1/m[1].s} -radix unsigned} {{/TestReadMem/the_dut/the_fil1/m[1].l} -radix unsigned} {{/TestReadMem/the_dut/the_fil1/m[1].k} -radix unsigned}}} {/TestReadMem/the_dut/the_fil1/m[1].j} {-height 27 -radix unsigned} {/TestReadMem/the_dut/the_fil1/m[1].i} {-height 27 -radix unsigned} {/TestReadMem/the_dut/the_fil1/m[1].s} {-height 27 -radix unsigned} {/TestReadMem/the_dut/the_fil1/m[1].l} {-height 27 -radix unsigned} {/TestReadMem/the_dut/the_fil1/m[1].k} {-height 27 -radix unsigned} {/TestReadMem/the_dut/the_fil1/m[2]} {-height 27 -radix unsigned} {/TestReadMem/the_dut/the_fil1/m[3]} {-height 27 -radix unsigned}} /TestReadMem/the_dut/the_fil1/m
add wave -noupdate /TestReadMem/the_dut/the_fil1/in_handsk
add wave -noupdate /TestReadMem/the_dut/the_fil1/out_handsk
add wave -noupdate /TestReadMem/the_dut/the_fil1/stop_r
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {430107673 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 165
configure wave -valuecolwidth 385
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {34385019 ps}
